// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Kj94MsMwvIAJYLpAOuemHBbYqZX2pH0',
    appId: '1:844861834658:web:bb0ac1430a5655d5261efb',
    messagingSenderId: '844861834658',
    projectId: 'cricket-team-manager-pro',
    authDomain: 'cricket-team-manager-pro.firebaseapp.com',
    storageBucket: 'cricket-team-manager-pro.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpJYBawbtXKS_DyUTYYiziJLMuwgMzHhk',
    appId: '1:844861834658:android:b03993019d9b94ca261efb',
    messagingSenderId: '844861834658',
    projectId: 'cricket-team-manager-pro',
    storageBucket: 'cricket-team-manager-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJh9svxesj5uThDVmLR94iPUDzysBnYbI',
    appId: '1:844861834658:ios:85e75a0c9d40e180261efb',
    messagingSenderId: '844861834658',
    projectId: 'cricket-team-manager-pro',
    storageBucket: 'cricket-team-manager-pro.appspot.com',
    iosBundleId: 'com.example.cricketTeamManagerPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJh9svxesj5uThDVmLR94iPUDzysBnYbI',
    appId: '1:844861834658:ios:fbe51a3217394ddc261efb',
    messagingSenderId: '844861834658',
    projectId: 'cricket-team-manager-pro',
    storageBucket: 'cricket-team-manager-pro.appspot.com',
    iosBundleId: 'com.example.cricketTeamManagerPro.RunnerTests',
  );
}
